### ISSUE TITLE
Please edit ReadMe

### ISSUE THREAD

**Issue by jordanpavlov** [xtranophilist/gnome-shell-extension-sensors#122]
The line "To build the extension for gnome-shell 3.10 or newer please run the following commands:"
is incorrect. This extension does not support version 3.16. Could you specify on what gnome-shell version are you working in the Project?

**Comment by adrianbroher** [comment]
> This extension does not support version 3.16.

This should have been fixed with commit 389b612.  Most of the time it's only the metadata.json.in file, that is not listing the shell-version supported.

> Could you specify on what gnome-shell version are you working in the Project?

I'm currently running 3.10.
