### ISSUE TITLE
I recieved this error - ubuntu 20.04lts - missing  " ( "

### ISSUE THREAD

**Issue by bettencb** [xtranophilist/gnome-shell-extension-sensors#150]
The settings of extension temperature@xtranophilist had an error:
```
SyntaxError: missing ( after for
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by Alex815O** [comment]
I had the same issue. There are syntax errors in three different files. 
Those files are in the directory:
>  ~/.local/share/gnome-shell/extensions/temperature@xtranophilist/
Files: 
- extension.js
- convenience.js
- utilities.js

You can open them with a text editor and replace every "for each" to "for".

**Comment by danielsanfr** [comment]
Same here!

**Comment by danielsanfr** [comment]
Why did you close PR? Is there any solution?

**Comment by bettencb** [comment]
yes, read above

**Comment by plibither8** [comment]
Even after fixing the instances of "for each" to "for", how do I reinitiate that extension, so it uses the changed code? This doesn't seem to be a solid fix :/
